version: "3.8"

services:
    php:
        container_name: php
        build:
            context: ./..
            dockerfile: ./docker/php/Dockerfile
            args:
                - PUID=${PUID}
                - PGID=${PGID}
                - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        volumes:
            - /var/www/vendor/
            - ./../:/var/www/
        ports:
            - ${NGINX_HOST_HTTP_PORT}:8080

    mysql:
        build:
            context: ./sql
        volumes:
            - db_data_mysql:/var/lib/minesql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306

volumes:
    db_data_mysql: